# Description
This dataset contains information about 3,900 customers and their purchase behavior in an e-commerce setting. The data spans various customer demographics, purchase preferences, and transactional details. It is designed to help analyze customer behavior, shopping patterns, and marketing effectiveness

In [1]:
import pandas as pd
customer_Shopping = pd.read_csv("shopping_trends.csv")

In [2]:
customer_Shopping

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

In [7]:
customer_Shopping.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [19]:
customer_Shopping.shape

(3900, 21)

In [8]:
customer_Shopping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 579.0+ KB

In [9]:
customer_Shopping.describe() # summary statics only provide numebrical column only

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [13]:
customer_Shopping.describe(include= "all") # summary statics only provide numebrical & non-numberical columns

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Credit Card,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,696,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [14]:
# To check missing Values

customer_Shopping.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [ ]:
customer_Shopping["Review Rating"] = (
    customer_Shopping.groupby('Category')["Review Rating"].transform(lambda x : x.fillna(x.median()))
)

# Fill the missing values review ratings using the median rating of the same product category.

In [20]:
# Check duplicate rows

customer_Shopping.duplicated().sum()

np.int64(0)

In [21]:
customer_Shopping.dtypes

customer_id                    int64
age                            int64
gender                        object
item_purchased                object
category                      object
purchase_amount                int64
location                      object
size                          object
color                         object
season                        object
review_rating                float64
subscription_status           object
payment_method                object
shipping_type                 object
discount_applied              object
promo_code_used               object
previous_purchases             int64
preferred_payment_method      object
frequency_of_purchases        object
age_group                   category
Purchase_frequency_days      float64
dtype: object

In [23]:
customer_Shopping["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [24]:
customer_Shopping["category"].unique()

array(['Clothing', 'Footwear', 'Outerwear', 'Accessories'], dtype=object)

In [25]:
customer_Shopping["age"].describe()

count    3900.000000
mean       44.068462
std        15.207589
min        18.000000
25%        31.000000
50%        44.000000
75%        57.000000
max        70.000000
Name: age, dtype: float64

In [6]:
# Make all the columns in lower case with _ ( This is best practice)

customer_Shopping.columns = customer_Shopping.columns.str.lower()
customer_Shopping.columns = customer_Shopping.columns.str.replace(' ','_')
customer_Shopping = customer_Shopping.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [7]:
customer_Shopping.columns # No all column names are moved to lower case for neat and consitence

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'payment_method',
       'shipping_type', 'discount_applied', 'promo_code_used',
       'previous_purchases', 'preferred_payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [10]:
# Create a  age_group column

# Create a new column to categorize customers by age.

customer_Shopping['age_group']=pd.cut(
    customer_Shopping['age'],
    bins =[0,18,35,50,100],
    labels=["Young", "Adult", "Middle-aged", "Senior"]
)

In [14]:
# This creates age groups that you can later use for customer analysis.
customer_Shopping[["age", "age_group"]].head(10)

   age    age_group
0   55       Senior
1   19        Adult
2   50  Middle-aged
3   21        Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27        Adult
8   26        Adult
9   57       Senior

In [17]:
# Create Column Purchase_frequency_days

frequency_mapping = {
    'Fortnighty' : 14,
    'Weekly' : 7,
    'Monthy' : 30,
    'Quartely' : 90,
    'Bi-Weekly' : 14,
    'Annunally' : 365,
    'Every 3 Months' : 90
}
customer_Shopping['Purchase_frequency_days'] = customer_Shopping['frequency_of_purchases'].map(frequency_mapping)

In [18]:
customer_Shopping[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [27]:
# To check whether discount_applied value is equal with Promo_code_used.

(customer_Shopping['discount_applied'] == customer_Shopping['promo_code_used']).all()

np.True_

In [29]:
customer_Shopping=customer_Shopping.drop('promo_code_used',axis = 1)

In [30]:
customer_Shopping.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'payment_method',
       'shipping_type', 'discount_applied', 'previous_purchases',
       'preferred_payment_method', 'frequency_of_purchases', 'age_group',
       'Purchase_frequency_days'],
      dtype='object')

In [ ]:
# promo_code_used column  is removed

In [31]:
# Install the MySQL connector (This installs the package that allows Python to communicate with MySQL.)

%pip install mysql-connector-python

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: mysql-connector-python in c:\users\kanie\appdata\local\programs\python\python310\lib\site-packages (26.7.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
# Import the connector

import mysql.connector

In [41]:
%pip install sqlalchemy mysql-connector-python

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.55-cp310-cp310-win_amd64.whl (2.2 MB)
     ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
     ---- ----------------------------------- 0.2/2.2 MB 6.9 MB/s eta 0:00:01
     ----------- ---------------------------- 0.6/2.2 MB 10.2 MB/s eta 0:00:01
     ---------------------------- ----------- 1.6/2.2 MB 11.1 MB/s eta 0:00:01
     ---------------------------------------- 2.2/2.2 MB 11.6 MB/s eta 0:00:00
Requirement already satisfied: mysql-connector-python in c:\users\kanie\appdata\local\programs\python\python310\lib\site-packages (26.7.0)
Collecting greenlet>=1
  Downloading greenlet-3.5.6-cp310-cp310-win_amd64.whl (322 kB)
     ---------------------------------------- 0.0/322.9 kB ? eta -:--:--
     ------------------------------------- 322.9/322.9 kB 19.5 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kanie\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.5.6 sqlalchemy-2.0.55
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# Connect to MySQL

In [42]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    drivername="mysql+mysqlconnector",
    username="root",
    password="Rogith@2014",
    host="localhost",
    port=3306,
    database="customer_shopping_behaviour"
)

engine = create_engine(connection_url)

print("Engine created successfully!")

Engine created successfully!

In [37]:
cursor = mydb.cursor()
cursor.execute("SHOW DATABASES")
print(cursor.fetchall())

[('customer_shopping_behaviour',), ('ecommerce_db',), ('first',), ('hospital_management',), ('information_schema',), ('mysql',), ('performance_schema',), ('project_1',), ('sakila',), ('sales__management',), ('sales_management',), ('school',), ('studentsdb',), ('sys',), ('world',)]

In [43]:
# Load the DataFrame into MySQL

customer_Shopping.to_sql(
    name="customer_shopping",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully!")

Data loaded successfully!

In [ ]:
# Check in mysql whether create dataset is synced in sql

select * from customer_shopping;

In [ ]:
# Preaparing few Business Questions using SQL

*** -- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) as total_revenue
FROM customer_shopping
GROUP BY gender;

# Now we know the renveue of male & female customers, where business wants to see the renveue split by gender, because this will help them to desgin better targerted campaings for each group.
==================================================================================================
-- Q2. Which customers used a discount but still spent more than the average purchase
amount?

select customer_id, purchase_amount
from customer_shopping
where discount_applied = 'Yes'
AND purchase_amount > ( 
select AVG(purchase_amount)
   FROM customer_shopping
  );

==================================================================================================
-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating),2) as avg_rating
from customer_shopping
group by item_purchased 
having count(*) > 5
ORDER BY avg_rating DESC
limit 5;


==================================================================================================
-Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount
from customer_shopping
where shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


==================================================================================================
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.


select subscription_status, count(customer_id) as total_customer, sum(purchase_amount) as total_revenue, round(avg(purchase_amount),2) as average_spend
from customer_shopping
where subscription_status IN ('Yes','No')	
group by subscription_status
order by total_revenue,average_spend desc;


 ==================================================================================================   
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, ROUND(AVG(discount_applied = 'Yes')*100,2) as discount_percentage
from customer_shopping
group by item_purchased 
order by discount_percentage desc
limit 5;

 ==================================================================================================   
***  --Q7. Segment customers into New, Returning, and Loyal based previous purchases, and show the count of each segment.

select 
case
when previous_purchases <=1 then 'New'
when previous_purchases <=10 then 'Returning'
else 'Loyal'
end as customer_segment,
count(*) as customer_count
from customer_shopping
group by customer_segment;
    
 ==================================================================================================   
-- Q8. What are the top 3 most purchased products within each ategory?

SELECT category, item_purchased, COUNT(*) AS purchase_count,
DENSE_RANK() OVER (
        PARTITION BY category
        ORDER BY COUNT(*) DESC
        ) AS product_rank
FROM customer_shopping
GROUP BY category, item_purchased
ORDER BY category, purchase_count DESC;

    
 ==================================================================================================   
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

    
 ==================================================================================================   
-- Q10. What is the revenue contribution of each age group?

In [3]:
customer_Shopping

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly